# model config
embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: 'BCE'

# Training and evaluation config
epochs: 20
train_batch_size: 4096
eval_batch_size: 4096
train_neg_sample_args: ~
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: labeled
metrics: ['RMSE', 'MAE', 'AUC', 'LogLoss']
valid_metric: RMSE
